package org.taymyr.lagom.openapi.autogenerate;

import akka.NotUsed;
import com.lightbend.lagom.javadsl.api.ServiceCall;
import org.taymyr.lagom.openapi.AbstractAutogeneratedOpenAPIService;

import java.util.Optional;

public class TestServiceImpl extends AbstractAutogeneratedOpenAPIService implements TestService {

    @Override
    public ServiceCall<NotUsed, Pets> listPets(Optional<Integer> limit) {
        return null;
    }

    @Override
    public ServiceCall<NotUsed, NotUsed> createPets() {
        return null;
    }

    @Override
    public ServiceCall<NotUsed, Pets> showPetById(String petId) {
        return null;
    }

}
