package org.taymyr.lagom.openapi.autogenerate;

import org.taymyr.lagom.openapi.AbstractAutogeneratedOpenAPIService;

public class EmptyTestServiceImpl extends AbstractAutogeneratedOpenAPIService implements EmptyTestService {
}
